# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Gem settings
title: 'AR Playkit'
twitter: 
  username: 'gerald_kim'
url: 'http://arplaykit.com'
author: 'Gerald Kim'

# Site settings
title: 'Gerald Kim'
url: 'http://arplaykit.com'
baseurl: ''
description: 'Playing around with ARKit'
permalink: pretty
logo: "/Resources/AR-icon.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
