exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock

site: Reality Playgrounds

url: 'http://realityplaygrounds.com'
baseurl: 

# Site settings
description: 'Playing around with ARKit'
logo: "/Resources/AR-icon.png"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown
social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/gerald.kim
  LinkedIn: https://www.linkedin.com/in/geraldkim
  GitHub: https://github.com/geraldk
  RSS: /feed.xml

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed
  timezone: Australia/Melbourne # Timezone for blog posts and alike

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
  